# Generated by Django 5.1.1 on 2024-10-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quartertly'), ('yearly', 'Yearly')], max_length=10)),
                ('start_date', models.DateField()),
            ],
        ),
    ]
