# Generated by Django 5.1.1 on 2024-09-29 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_rename_buying_report_buyingreport_generatereport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuyingReport',
            new_name='Feedback',
        ),
    ]
