# Generated by Django 5.1.1 on 2024-10-04 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_salesperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='quantity_sold',
        ),
    ]
